- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_admin_username is defined) and (keycloak_admin_username|length > 0)
      - (keycloak_admin_password is defined) and (keycloak_admin_password|length > 0)
      - (client_id is defined) and (client_id|length > 0)

- include_tasks: authentication/get_admin_access_token.yml

- name: "Get OIDC Keycloak JSON of '{{ client_id }}'"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ client_id }}"
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: keycloak_response

- set_fact:
    keylcoak_client: "{{ keycloak_response.json | first }}"

- name: "Get OIDC Keycloak JSON of '{{ client_id }}'"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/clients/{{ keylcoak_client.id }}/installation/providers/keycloak-oidc-keycloak-json"
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: keycloak_response

- set_fact:
    keycloak_oidc_json: "{{ keycloak_response.json }}"

- name: "Ensures {{ output_path_local }} dir exists"
  delegate_to: localhost
  file:
    path: "{{ output_path_local }}"
    state: directory
  when: (output_path_local is defined) and (output_path_local|length > 0)
- name: "Copy OIDC installation configuration in JSON file"
  delegate_to: localhost
  copy:
    content: "{{ keycloak_oidc_json }}"
    dest: "{{ output_path_local }}/{{ keycloak_realm}}-keycloak.json"
  when: (output_path_local is defined) and (output_path_local|length > 0)

- name: "Ensures {{ output_path_target_host }} dir exists"
  file:
    path: "{{ output_path_target_host }}"
    state: directory
  when: (output_path_target_host is defined) and (output_path_target_host|length > 0)
- name: "Copy OIDC installation configuration in JSON file"
  copy:
    content: "{{ keycloak_oidc_json }}"
    dest: "{{ output_path_target_host }}/{{ keycloak_realm}}-keycloak.json"
  when: (output_path_target_host is defined) and (output_path_target_host|length > 0)
