- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_admin_username is defined) and (keycloak_admin_username|length > 0)
      - (keycloak_admin_password is defined) and (keycloak_admin_password|length > 0)
      - (client_id is defined) and (client_id|length > 0)

- include_tasks: authentication/get_admin_access_token.yml

- name: "Get uuid of '{{ client_id }}'"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ client_id }}"
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: output_get_client

- set_fact:
    client_uuid: "{{ output_get_client.json[0].id }}"

- name: "Get secret of '{{ client_id }}'"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/clients/{{ client_uuid }}/client-secret"
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
  register: output_get_client

- set_fact:
    client_secret: "{{ output_get_client.json.value }}"
