vault_config_directory: "/vault/config"
vault_token_file: "{{ vault_config_directory }}/root/root_token"

vault_approles:
  - name: "resource-registry"
    config_store_directory: "{{ vault_config_directory }}/resource-registry"
    policies:
      - name: "resource-registry"
        policy: "\npath \"sys/policy/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] } \npath \"sys/auth\" { capabilities = [\"read\"] } \npath \"/identity/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] } \npath \"resources/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] }"
  - name: "service-registry"
    config_store_directory: "{{ vault_config_directory }}/service-registry"
    policies:
      - name: "service-registry"
        policy: "\npath \"sys/policy/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] } \npath \"sys/auth\" { capabilities = [\"read\"] } \npath \"/identity/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] } \npath \"services/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] } \npath \"service-repositories/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] }"
  - name: awx
    config_store_directory: "{{ vault_config_directory }}/awx"
    policies:
      - name: "awx"
        policy: "path \"resources/*\" { capabilities = [\"read\", \"list\", \"create\", \"update\"] } \npath \"service-repositories/*\" { capabilities = [\"read\", \"list\"] }"
  - name: awx-jwt-proxy
    config_store_directory: "{{ vault_config_directory }}/awx-jwt-proxy"
    policies:
      - name: "awx-jwt-proxy"
        policy: "path \"awx-jwt-proxy/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] }"

vault_kv_secret_engines:
  - "awx-jwt-proxy"
  - "resources"
  - "services"
  - "service-repositories"
