- name: "Check if Consul configuration file '{{ consul_token_file }}' exists"
  stat:
    path: "{{ consul_token_file }}"
  register: stat_result
  until:
    - stat_result.stat.exists
  retries: 1000
  delay: 1

- name: "Read Consul token from file '{{ consul_token_file }}'"
  set_fact:
    consul_token: "{{ lookup('file', consul_token_file) }}"

- assert:
    that:
      - (consul_token is defined) and (consul_token|length > 0)
    fail_msg: "Import of Consul token from file '{{ consul_token_file }}' failed"
