resource-registry:
  url: http://{{ resource_registry_host }}:{{ resource_registry_port }}
  init-directory: init/

keycloak:
  auth-server-url: {{ keycloak_auth_server_url }}
  realm: fabos
  username: fabos
  password: password
