- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_realm_role is defined) and (keycloak_realm_role|length > 0)

- name: "Create realm role '{{ keycloak_realm_role }}'"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/roles"
    method: POST
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
    body_format: json
    body:
      name: "{{ keycloak_realm_role.name }}"
    status_code: 201, 409
  register: output_post_realm_role
  changed_when: output_post_realm_role.status == 201
