server:
    port: 8051

spring:
    application:
        name: awx_jwt_proxy
    banner:
        location: banner.txt
    security:
      user:
          name: admin
          password: password

keycloak:
    auth-server-url: {{ keycloak_auth_server_url }}
    realm: fabos
    resource: {{ keycloak_awx_jwt_proxy_config.resource }}
    credentials:
        secret: {{ keycloak_awx_jwt_proxy_config.credentials.secret }}
    use-resource-role-mappings: false
    bearer-only: true

awx:
    hostname: {{ awx_hostname }}
    scheme: {{ awx_scheme }}
    port: {{ awx_port }}
    username: {{ awx_jwt_proxy_username }}
    password: {{ awx_jwt_proxy_password }}
    organization-name: Service Lifecycle Management
    team-name: user

vault:
    scheme: {{ vault_scheme }}
    host: {{ vault_hostname }}
    port: {{ vault_port }}
    authentication: {{ vault_awx_jwt_proxy_authentication }}
    token: s.t8H97SyHrPpHfLODxuIndeJ6
    app-role:
        app-role-path: approle
        role-id: {{ vault_awx_jwt_proxy_app_role_id }}
        secret-id: {{ vault_awx_jwt_proxy_app_secret_id }}
    kv-mount-path: awx-jwt-proxy
