- name: "Add project '{{ awx_project.project_name }}'"
  awx.awx.project:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_admin_username }}"
    controller_password: "{{ awx_admin_password }}"
    name: "{{ awx_project.project_name }}"
    description: "{{ awx_project.project_description }}"
    organization: "{{ awx_slm_organization_name }}"
    state: present
    scm_type: git
    scm_url: "{{ item.scm_url }}"
    scm_branch: "{{ item.scm_branch | default('') }}"
    scm_credential: "{{ awx_scm_credential_name }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch | default('false') }}"
  timeout: 60
  ignore_errors: true

- name: "Set read permissions for project '{{ awx_project.project_name }}'"
  awx.awx.role:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_admin_username }}"
    controller_password: "{{ awx_admin_password }}"
    team: user
    role: read
    projects:
      - "{{ awx_project.project_name }}"
    state: present
  ignore_errors: true

- name: "Create Job Templates for project '{{ awx_project.project_name }}'"
  awx.awx.job_template:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_admin_username }}"
    controller_password: "{{ awx_admin_password }}"
    name: "{{ job_template.template_name }}"
    job_type: run
    project: "{{ awx_project.project_name }}"
    playbook: "{{ job_template.playbook }}"
    inventory: "Default"
    credentials:
      - "Consul"
      - "HashiCorp Vault"
    state: present
    fact_caching_enabled: yes
    ask_variables_on_launch: yes
  with_items: "{{ awx_project.job_templates }}"
  ignore_errors: true
  loop_control:
    loop_var: job_template

- name: "Set read permissions for job templates '{{ awx_project.project_name }}'"
  awx.awx.role:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_admin_username }}"
    controller_password: "{{ awx_admin_password }}"
    team: user
    role: execute
    job_templates:
      - "{{ job_template.template_name }}"
    state: present
  with_items: "{{ awx_project.job_templates }}"
  ignore_errors: true
  loop_control:
    loop_var: job_template
