- assert:
    that:
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_token is defined) and (vault_token|length > 0)
      - (approle_name is defined) and (approle_name|length > 0)
      - (new_approle_token_policy is defined) and (new_approle_token_policy|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Get token policies of '{{ approle_name }}'"
  uri:
    url: "{{ vault_url }}/v1/auth/approle/role/{{ approle_name }}/policies"
    validate_certs: no
    method: GET
    headers:
      Authorization: "Bearer {{ vault_token }}"
    status_code: 200
  register: output_approle_policies
  no_log: true

- set_fact:
    token_policies: "{{ output_approle_policies.json.data.token_policies }}"

- set_fact:
    token_policies: "{{ (token_policies + [ new_approle_token_policy ]) | unique }}"

- name: "Write Token Policies of '{{ approle_name }}'"
  uri:
    url: "{{ vault_url }}/v1/auth/approle/role/{{ approle_name }}/policies"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    status_code: 200, 204
    body_format: json
    body:
      token_policies: "{{ token_policies | join(',') }}"
  register: output_approle_policies
  no_log: true
