- assert:
    that:
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_token is defined) and (vault_token|length > 0)
      - (mount_auth_path is defined) and (mount_auth_path|length > 0)
      - (oidc_discovery_url is defined) and (oidc_discovery_url|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Mount auth path '{{ mount_auth_path }}'"
  uri:
    url: "{{ vault_url }}/v1/sys/auth/{{ mount_auth_path }}"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      type: jwt
    status_code: 204, 400
  register: output_mount_auth_path
  changed_when: output_mount_auth_path.status == 204

- name: "Set base url for auth path '{{ mount_auth_path }}'"
  set_fact:
    base_url: "{{ vault_url }}/v1/auth/{{ mount_auth_path }}"

- debug:
    var: oidc_discovery_url

- name: "Create config for auth path '{{ mount_auth_path }}'"
  uri:
    url: "{{ base_url }}/config"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      oidc_discovery_url: "{{ oidc_discovery_url }}"
      oidc_discovery_ca_pem: "{{ oidc_discovery_ca_pem | default('') }}"
      oidc_client_id: "{{ oidc_client_id | default('') }}"
      bound_issuer: "{{ bound_issuer | default('') }}"
    status_code: 204

- name: "Create default role for auth path '{{ mount_auth_path }}'"
  uri:
    url: "{{ base_url }}/role/default"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      name: default
      role_type: jwt
      token_ttl: 3600
      token_max_ttl: 3600
      user_claim: sub
      bound_audiences:
        - "self-service-portal"
        - "resource-registry"
        - "service-registry"
      claim_mappings:
        preferred_username: username
        email: email
      allowed_redirect_uris:
        - "*"
      groups_claim: "/realm_access/roles"
    status_code: 200,204
