- assert:
    that:
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_token is defined) and (vault_token|length > 0)
      - (policy_name is defined) and (policy_name|length > 0)
      - (policy_content is defined) and (approle_name|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Create policy '{{ policy_name }}'"
  uri:
    url: "{{ vault_url }}/v1/sys/policy/{{ policy_name }}"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      policy: "{{ policy_content }}"
    status_code: 204, 400 # 400 means policy at path exists already
  register: output_create_policy
  changed_when: output_create_policy.status == 204
