- assert:
    that:
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_token is defined) and (vault_token|length > 0)
      - (kv_secret_engine_name is defined) and (kv_secret_engine_name|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Create KV secret engine '{{ kv_secret_engine_name }}'"
  uri:
    url: "{{ vault_url }}/v1/sys/mounts/{{ kv_secret_engine_name }}"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      type: kv
      description: "{{ kv_secret_engine_description| default('') }}"
      options:
        version: "{{ kv_secret_engine_version | default('2') }}"
    status_code: 204, 400
  register: output_create_kv_secret_engine
  changed_when: output_create_kv_secret_engine.status == 204
