- assert:
    that:
      - (vault_url is defined) and (vault_url|length > 0)
      - (vault_token is defined) and (vault_url|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Create app role Auth Method 'approle'"
  uri:
    url: "{{ vault_url }}/v1/sys/auth/approle"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ vault_token }}"
    body_format: json
    body:
      type: approle
    status_code: 204, 400 # 400 means auth method at path exists already
  register: output_create_approle
  changed_when: output_create_approle.status == 204
