- include_tasks: actions/create_approle.yml

- debug:
    var: approle_policies

- block:
  - include_tasks: actions/create_policy.yml
    vars:
      policy_name: "{{ item.name }}"
      policy_content: "{{ item.policy }}"
    with_items: "{{ approle_policies }}"

  - include_tasks: actions/add_policy_to_approle.yml
    vars:
      new_approle_token_policy: "{{ item.name }}"
    with_items: "{{ approle_policies }}"

  when: (approle_policies|length > 0)
