- name: "Init FaboOS Service Lifecycle Management"
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Import configuration from environment variables"
      block:
        - set_fact:
            awx_url: "{{ lookup('env', 'AWX_URL') }}"                                       # URL of AWX instance which should be initialized
            awx_admin_user: "{{ lookup('env', 'AWX_ADMIN_USERNAME') }}"                     # Username of AWX admin user
            awx_admin_username: "{{ lookup('env', 'AWX_ADMIN_USERNAME') }}"                 # Username of AWX admin user
            awx_admin_password: "{{ lookup('env', 'AWX_ADMIN_PASSWORD') }}"                 # Password of AWX admin user
            awx_scm_username: "{{ lookup('env', 'AWX_SCM_USERNAME') }}"                     # Username of SCM user to import projects in AWX
            awx_scm_password: "{{ lookup('env', 'AWX_SCM_PASSWORD') }}"                     # Password of SCM user to import projects in AWX
            awx_jwt_proxy_awx_username: "{{ lookup('env', 'AWX_JWT_PROXY_USERNAME') }}"     # Username of user for AWX JWT proxy
            awx_jwt_proxy_awx_password: "{{ lookup('env', 'AWX_JWT_PROXY_PASSWORD') }}"     # Password of user for AWX JWT proxy
            consul_config_via: "{{ lookup('env', 'CONSUL_CONFIG_VIA') }}"                   # Defines how the configuration of Consul is defined (SHARED_VOLUME or ENVIRONMENT_VARIABLES)
            consul_token: "{{ lookup('env', 'CONSUL_TOKEN') }}"
            vault_config_via: "{{ lookup('env', 'VAULT_CONFIG_VIA') }}"                     # Defines how the configuration of Vault is defined (SHARED_VOLUME or ENVIRONMENT_VARIABLES)
            vault_approle_role_id: "{{ lookup('env', 'VAULT_APPROLE_ROLE_ID') }}"
            vault_approle_secret_id: "{{ lookup('env', 'VAULT_APPROLE_SECRET_ID') }}"

        - debug:
            var: vault_root_token

        - assert:
            that:
              - (awx_url is defined) and (awx_url|length > 0)
              - (awx_admin_user is defined) and (awx_admin_user|length > 0)
              - (awx_admin_username is defined) and (awx_admin_username|length > 0)
              - (awx_admin_password is defined) and (awx_admin_password|length > 0)
              - (awx_scm_username is defined) and (awx_scm_username|length > 0)
              - (awx_scm_password is defined) and (awx_scm_password|length > 0)
              - (awx_jwt_proxy_awx_username is defined) and (awx_jwt_proxy_awx_username|length > 0)
              - (awx_jwt_proxy_awx_password is defined) and (awx_jwt_proxy_awx_password|length > 0)
            fail_msg: "Variable must be defined and not empty"

        - assert:
            that:
              - (consul_config_via == 'SHARED_VOLUME') or (consul_config_via == 'ENVIRONMENT_VARIABLES')
              - (vault_config_via == 'SHARED_VOLUME') or (vault_config_via == 'ENVIRONMENT_VARIABLES')
            fail_msg: "Variable value must be 'SHARED_VOLUME' or 'ENVIRONMENT_VARIABLES'"

        - assert:
            that:
              - (consul_token is defined) and (consul_token|length > 0)
            fail_msg: "When Consul is configured via environment variables, environment variable 'CONSUL_TOKEN' must be set"
          when: consul_config_via == 'ENVIRONMENT_VARIABLES'
        - assert:
            that:
              - (vault_approle_role_id is defined) and (vault_approle_role_id|length > 0)
              - (vault_approle_secret_id is defined) and (vault_approle_secret_id|length > 0)
            fail_msg: "When Vault is configured via environment variables, environment variables 'VAULT_APPROLE_ROLE_ID' nad 'VAULT_APPROLE_SECRET_ID' must be set"
          when: vault_config_via == 'ENVIRONMENT_VARIABLES'

    - name: "Import Consul configuration from shared volume"
      include_role:
        name: awx_init
        tasks_from: helper/consul_import_config_shared_volume.yml
      when: consul_config_via == 'SHARED_VOLUME'

    - name: "Import Vault configuration from shared volume"
      include_role:
        name: awx_init
        tasks_from: helper/vault_import_config_shared_volume.yml
      when: vault_config_via == 'SHARED_VOLUME'

    - name: "Wait for AWX being up"
      uri:
        url: "{{ awx_url }}"
        status_code: 200
      register: result
      until:
        - result.status == 200
        - not 'migrations_notran' in result.url
      retries: 120
      delay: 3

    - include_role:
        name: awx_init
        tasks_from: awx_load_data.yml

