- name: "Init Vault"
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Import configuration from environment variables"
      block:
        - set_fact:
            vault_url: "{{ lookup('env', 'VAULT_URL') }}"                       # URL of Vault instance which should be initialized
            vault_config_via: "{{ lookup('env', 'VAULT_CONFIG_VIA') }}"         # Defines how the configuration of Vault is defined (SHARED_VOLUME or ENVIRONMENT_VARIABLES)
            vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
            keycloak_auth_url: "{{ lookup('env', 'KEYCLOAK_AUTHSERVERURL') }}"  # Auth URL of Keycloak instance
            keycloak_realm: "{{ lookup('env', 'KEYCLOAK_REALM') }}"             # Realm of Keycloak instance which should be used for JWT authentication

        - assert:
            that:
              - (vault_url is defined) and (vault_url|length > 0)
            fail_msg: "Variable must be defined and not empty"

        - assert:
            that:
              - (vault_config_via == 'SHARED_VOLUME') or (vault_config_via == 'ENVIRONMENT_VARIABLES')
            fail_msg: "Variable value must be 'SHARED_VOLUME' or 'ENVIRONMENT_VARIABLES'"

    - name: "Import Vault configuration from shared volume"
      include_role:
        name: vault_init
        tasks_from: helper/vault_import_config_shared_volume.yml
      when: vault_config_via == 'SHARED_VOLUME'

    - include_role:
        name: vault_init
        tasks_from: vault_init.yml
