- assert:
    that:
      - awx_url
      - awx_username
      - awx_password
      - awx_organization_name

- name: "Get organizations"
  uri:
    url: "{{ awx_url }}/api/v2/organizations"
    method: GET
    force_basic_auth: yes
    url_username: "{{ awx_username }}"
    url_password: "{{ awx_password }}"
    status_code: 200
  register: output_get_organizations

- set_fact:
    awx_organization: "{{ output_get_organizations.json.results | json_query(query) | first }} "
  vars:
    query: "[?name=='{{ awx_organization_name }}']"
