- name: "Check if Vault configuration files in directory '{{ vault_config_directory }}' exists"
  stat:
    path: "{{ item }}"
  register: stat_result
  until:
    - stat_result.stat.exists
  retries: 1000
  delay: 1
  with_items:
    - "{{ vault_approle_role_id_file }}"
    - "{{ vault_approle_secret_id_file }}"

- name: "Read Vault app role id from file '{{ vault_approle_role_id_file }}'"
  set_fact:
    vault_approle_role_id: "{{ lookup('file', vault_approle_role_id_file) }}"

- name: "Read Vault token from file '{{ vault_approle_secret_id_file }}'"
  set_fact:
    vault_approle_secret_id: "{{ lookup('file', vault_approle_secret_id_file) }}"

- assert:
    that:
      - (vault_approle_role_id is defined) and (vault_approle_role_id|length > 0)
      - (vault_approle_secret_id is defined) and (vault_approle_secret_id|length > 0)
    fail_msg: "Import of Vault app role from files '{{ vault_approle_role_id_file }}' and '{{ vault_approle_secret_id_file }}' failed"

