keycloak_clients:
  - client_id: awx-jwt-authenticator
    public_client: false
    service_accounts_enabled: false
    oidc_installation_json_output_path_local: "/config/awx-jwt-authenticator"
  - client_id: self-service-portal
    public_client: true
    service_accounts_enabled: false
  - client_id: resource-registry
    public_client: false
    service_accounts_enabled: true
    oidc_installation_json_output_path_local: "/config/resource-registry"
  - client_id: service-registry
    public_client: false
    service_accounts_enabled: true
    oidc_installation_json_output_path_local: "/config/service-registry"
  - client_id: notification-service
    public_client: false
    service_accounts_enabled: false
    oidc_installation_json_output_path_local: "/config/notification-service"

keycloak_realms:
  - realm: "fabos"
    displayName: ""
    displayNameHtml: ""
    enabled: true
    loginTheme: "fabos"

keycloak_realm: fabos

keycloak_realm_roles:
  - name: ssp-user
    isDefault: true
  - name: slm-admin
    isDefault: false

keycloak_default_user:
  username: fabos
  enabled: true
  credentials:
    - type: password
      value: password
      temporary: false
  realmRoles: [ "ssp-user", "slm-admin" ]

keycloak_client_configs_store_directory: "/config/service-registry-init"
