- name: "Check if Vault configuration file '{{ vault_token_file }}' exists"
  stat:
    path: "{{ vault_token_file }}"
  register: stat_result
  until:
    - stat_result.stat.exists
  retries: 1000
  delay: 1

- name: "Read Vault token from file '{{ vault_token_file }}'"
  set_fact:
    vault_token: "{{ lookup('file', vault_token_file) }}"

- assert:
    that:
      - (vault_token is defined) and (vault_token|length > 0)
    fail_msg: "Import of Vault token from file '{{ vault_token_file }}' failed"
