awx_slm_organization_name: "Service Lifecycle Management"

awx_credential_types:
  - name: Consul
    inputs:
      fields:
        - id: consul_url
          type: string
          label: Consul URL
          multiline: false
        - id: consul_token
          type: string
          label: Consul Token
          secret: true
          multiline: false
      required:
        - consul_url
        - consul_token
    injectors:
      env:
        CONSUL_TOKEN: "{% raw %}{{ consul_token }}{% endraw %}"
        CONSUL_URL: "{% raw %}{{ consul_url }}{% endraw %}"
  - name: HashiCorp Vault
    inputs:
      fields:
        - id: vault_url
          type: string
          label: Vault URL
          secret: false
          multiline: false
        - id: vault_approle_role_id
          type: string
          label: Vault App Role - Role ID
          secret: false
          multiline: false
        - id: vault_approle_secret_id
          type: string
          label: Vault App Role - Secret ID
          secret: true
          multiline: false
      required:
        - vault_url
        - vault_approle_role_id
        - vault_approle_secret_id
    injectors:
      env:
        VAULT_URL: "{% raw %}{{ vault_url }}{% endraw %}"
        VAULT_APPROLE_ROLE_ID: "{% raw %}{{ vault_approle_role_id }}{% endraw %}"
        VAULT_APPROLE_SECRET_ID: "{% raw %}{{ vault_approle_secret_id }}{% endraw %}"

awx_credentials:
  - name: Consul
    credential_type: Consul
    inputs:
      consul_url: "http://consul:8500"
      consul_token: "{{ consul_token }}"
  - name: HashiCorp Vault
    credential_type: HashiCorp Vault
    inputs:
      vault_url: "http://vault:8200"
      vault_approle_role_id: "{{ vault_approle_role_id }}"
      vault_approle_secret_id: "{{ vault_approle_secret_id }}"

ansible_projects_and_templates: []

consul_config_directory: "/config/consul"
consul_token_file: "{{ consul_config_directory }}/consul_token"

vault_config_directory: "/config/vault"
vault_approle_role_id_file: "{{ vault_config_directory }}/role_id"
vault_approle_secret_id_file: "{{ vault_config_directory }}/secret_id"

notification_service_config_directory: "/config/notification-service"
notification_service_username_file: "{{ notification_service_config_directory }}/awx_username"
notification_service_password_file: "{{ notification_service_config_directory }}/awx_password"

resource_registry_config_directory: "/config/resource-registry"
resource_registry_username_file: "{{ resource_registry_config_directory }}/awx_username"
resource_registry_password_file: "{{ resource_registry_config_directory }}/awx_password"

service_registry_config_directory: "/config/service-registry"
service_registry_username_file: "{{ service_registry_config_directory }}/awx_username"
service_registry_password_file: "{{ service_registry_config_directory }}/awx_password"
