version: '3'

services:

  consul:
    image: fabos4ai/slm-consul:${CONSUL_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    networks:
      default:
        aliases:
          - consul
    ports:
      - "${CONSUL_PORT}:8500"
    volumes:
      - consul_data:/consul/data
      - consul_config_root:/config/root
      - consul_config_awx:/config/awx
      - consul_config_resource-registry:/config/resource_registry
      - consul_config_service-registry:/config/service_registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8500" ]
    depends_on:
      - keycloak

  consul-init:
    image: fabos4ai/slm-consul-init:${SLM_VERSION}
    restart: "no"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - consul_config_root:/config/consul/root
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  consul-esm:
    image: hashicorp/consul-esm:${CONSUL_ESM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - consul
    environment:
      CONSUL_HTTP_ADDR: consul:8500
    volumes:
      - consul_config_root:/consul/
    command: >
      sh -c "export CONSUL_HTTP_TOKEN=$$(cat /consul/consul_master_token) && consul-esm"

volumes:
  consul_data:
  consul_config_root:
  consul_config_awx:
  consul_config_resource-registry:
  consul_config_service-registry:
