version: '3'

services:
  keycloak:
    image: fabos4ai/slm-keycloak:${KEYCLOAK_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-database
    environment:
      KC_HOSTNAME: ${SLM_HOSTNAME}
    volumes:
      - keycloak-database_config:/keycloak/database/config
    networks:
      default:
        aliases:
          - 'keycloak'
    env_file:
      - "config/keycloak.env"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/auth" ]

  keycloak-init:
    image: fabos4ai/slm-keycloak-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    env_file:
      - "config/keycloak.env"
    volumes:
      - keycloak_config_awx-jwt-authenticator:/config/awx-jwt-authenticator
      - keycloak_config_notification-service:/config/notification-service
      - keycloak_config_resource-registry:/config/resource-registry
      - keycloak_config_service-registry:/config/service-registry
      - keycloak_config_service-registry-init:/config/service-registry-init
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  keycloak-database:
    image: fabos4ai/mariadb:${KEYCLOAK_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    volumes:
      - keycloak-database_data:/var/lib/mysql
      - keycloak-database_config:/config
    ports:
      - "4406:3306"
    networks:
      default:
        aliases:
          - keycloak-database
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

volumes:
  keycloak-database_data:
  keycloak-database_config:
  keycloak_config_awx-jwt-authenticator:
  keycloak_config_notification-service:
  keycloak_config_resource-registry:
  keycloak_config_service-registry:
  keycloak_config_service-registry-init:
