version: '3'

services:

  awx-fixed-files:
    image: fabos4ai/slm-awx-fixed-files:${AWX_VERSION}
    build: ../src/awx/awx-fixed-files

  awx-web:
    build: ../src/awx/awx-web

  awx-task:
    build: ../src/awx/awx-task

  awx-postgres:
    build: ../src/awx/awx-postgres

  awx-init:
    build: ../src/awx/awx-init

  keycloak:
    build: ../src/keycloak/keycloak

  keycloak-init:
    build: ../src/keycloak/keycloak-init

  keycloak-database:
    build: ../src/keycloak/keycloak-db

  vault:
    build: ../src/vault/vault

  vault-init:
    build: ../src/vault/vault-init/

  consul:
    build: ../src/consul/consul

  consul-init:
    build: ../src/consul/consul-init/

  config-exporter:
    build: ../src/config-exporter


