version: '3'

services:
  ###region AWX
  awx-web:
    image: fabos4ai/slm-awx-web:${AWX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis
      - awx-redis-init
      - awx-postgres
    ports:
      - "${AWX_PORT_HTTP}:8052"
      - "${AWX_PORT_HTTPS}:8053"
    networks:
      default:
        aliases:
          - awxweb
    user: root
    volumes:
      - awx_supervisor_socket:/var/run/supervisor
      - awx_rsyslog_socket:/var/run/awx-rsyslog/
      - awx_rsyslog_config:/var/lib/awx/rsyslog/
      - awx-redis:/var/run/redis
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8052" ]

  awx-task:
    image: fabos4ai/slm-awx-task:${AWX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis
      - awx-redis-init
      - awx-web
      - awx-postgres
    networks:
      default:
        aliases:
          - awx
    user: root
    volumes:
      - awx_supervisor_socket:/var/run/supervisor
      - awx_rsyslog_socket:/var/run/awx-rsyslog/
      - awx_rsyslog_config:/var/lib/awx/rsyslog/
      - awx-redis:/var/run/redis

  awx-jwt-authenticator:
    image: fabos4ai/slm-awx-jwt-authenticator:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8051/swagger-ui.html" ]
    ports:
      - "8051:8051"
    networks:
      default:
        aliases:
          - awx-jwt-authenticator
    volumes:
      - vault_config_awx-jwt-proxy:/opt/vault/awx-jwt-proxy:ro
      - awx_config_jwt-proxy:/app/awx
      - keycloak_config_awx-jwt-proxy:/app/keycloak
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  awx-redis:
    image: fabos4ai/awx-redis:${AWX_REDIS_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis-init
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: [ "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - awx-redis:/var/run/redis/
    healthcheck:
      test: [ "CMD", "redis-cli", "-s", "/var/run/redis/redis.sock", "ping" ]

  awx-redis-init:
    image: busybox
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    command: sh -c "cd /var/run/redis/ && chmod -R 777 ."
    volumes:
      - awx-redis:/var/run/redis/

  awx-postgres:
    image: fabos4ai/slm-awx-postgres:${AWX_POSTGRES_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      PGUSER: awx
    volumes:
      - "awx_database_data:/var/lib/postgresql/data:Z"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]

  awx-init:
    image: fabos4ai/slm-awx-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-web
      - awx-task
      - awx-jwt-authenticator
      - awx-redis
      - awx-redis-init
      - awx-postgres
    volumes:
      - awx_config_notification-service:/config/notification-service
      - awx_config_resource-registry:/config/resource-registry
      - awx_config_service-registry:/config/service-registry
      - awx_config_jwt-proxy:/config/awx-jwt-proxy
      - consul_config_awx:/config/consul
      - vault_config_awx:/config/vault
  ###endregion AWX

  ###region Custom Service Lifecycle Components
  ui:
    image: fabos4ai/slm-ui:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${UI_PORT}:80"
    networks:
      default:
        aliases:
          - ui
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    environment:
      VUE_APP_KEYCLOAK_URL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]

  resource-registry:
    image: fabos4ai/slm-resource-registry:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    ports:
      - "${RESOURCE_REGISTRY_PORT}:9010"
    networks:
      default:
        aliases:
          - resource-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - awx_config_resource-registry:/app/awx:ro
      - consul_config_resource-registry:/app/consul:ro
      - keycloak_config_resource-registry:/app/keycloak:ro
      - vault_config_resource-registry:/app/vault:ro
      - resource-registry-database_config:/app/database/config
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9010/swagger-ui/index.html" ]

  resource-registry-database:
    image: fabos4ai/mariadb:${RESOURCE_REGISTRY_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${RESOURCE_REGISTRY_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - resource-registry-database
    environment:
      MYSQL_USER: resource-registry
      MYSQL_DATABASE: resources
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - resource-registry-database_data:/var/lib/mysql
      - resource-registry-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  resource-registry-init:
    image: fabos4ai/slm-resource-registry-init:${SLM_VERSION}
    restart: "no"
    depends_on:
      - resource-registry
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  service-registry:
    image: fabos4ai/slm-service-registry:${SLM_VERSION}
    restart: unless-stopped
    depends_on:
      - service-registry-database
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    ports:
      - "${SERVICE_REGISTRY_PORT}:9020"
    networks:
      default:
        aliases:
          - service-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - awx_config_service-registry:/app/awx:ro
      - consul_config_service-registry:/app/consul:ro
      - keycloak_config_service-registry:/app/keycloak:ro
      - vault_config_service-registry:/app/vault:ro
      - service-registry-database_config:/app/database/config
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9020/swagger-ui/index.html" ]

  service-registry-init:
    image: fabos4ai/slm-service-registry-init:${SLM_VERSION}
    restart: "no"
    depends_on:
      - service-registry
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - keycloak_config_service-registry-init:/app/keycloak
      - ./init/service-registry:/init

  service-registry-database:
    image: fabos4ai/mariadb:${SERVICE_REGISTRY_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${SERVICE_REGISTRY_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - service-registry-database
    environment:
      MYSQL_USER: service-registry
      MYSQL_DATABASE: services
    volumes:
      - service-registry-database_data:/var/lib/mysql
      - service-registry-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  notification-service:
    image: fabos4ai/slm-notification-service:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:9001"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    networks:
      default:
        aliases:
          - notification-service
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9001/swagger-ui/index.html" ]
    volumes:
      - awx_config_notification-service:/app/awx:ro
      - keycloak_config_notification-service:/app/keycloak:ro
      - notification-service-database_config:/app/database/config

  notification-service-database:
    image: fabos4ai/mariadb:${NOTIFICATION_SERVICE_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${NOTIFICATION_SERVICE_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - notification-service-database
    environment:
      MYSQL_USER: notification-service
      MYSQL_DATABASE: notifications
    volumes:
      - notification-service-database_data:/var/lib/mysql
      - notification-service-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  ###endregion Custom Service Lifecycle Components

  ###region Keycloak
  keycloak:
    image: fabos4ai/slm-keycloak:${KEYCLOAK_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-database
    volumes:
      - keycloak-database_config:/keycloak/database/config
    networks:
      default:
        aliases:
          - 'keycloak'
    env_file:
      - "config/keycloak.env"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/auth" ]

  keycloak-init:
    image: fabos4ai/slm-keycloak-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    env_file:
      - "config/keycloak.env"
    volumes:
      - keycloak_config_awx-jwt-proxy:/config/awx-jwt-proxy
      - keycloak_config_notification-service:/config/notification-service
      - keycloak_config_resource-registry:/config/resource-registry
      - keycloak_config_service-registry:/config/service-registry
      - keycloak_config_service-registry-init:/config/service-registry-init
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  keycloak-database:
    image: fabos4ai/mariadb:${KEYCLOAK_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    volumes:
      - keycloak-database_data:/var/lib/mysql
      - keycloak-database_config:/config
    ports:
      - "4406:3306"
    networks:
      default:
        aliases:
          - keycloak-database
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  ###endregion Keycloak

  ###region Vault
  vault:
    image: fabos4ai/slm-vault:${VAULT_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${VAULT_PORT}:8200"
    networks:
      default:
        aliases:
          - vault
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - vault_config_root:/vault/config/root
      - vault_data:/vault/file
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: export VAULT_ADDR=http://127.0.0.1:8200 && vault status

  vault-init:
    image: fabos4ai/slm-vault-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - vault
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - vault_config_root:/vault/config/root
      - vault_config_awx:/vault/config/awx
      - vault_config_awx-jwt-proxy:/vault/config/awx-jwt-proxy
      - vault_config_resource-registry:/vault/config/resource-registry
      - vault_config_service-registry:/vault/config/service-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
  ###endregion Vault

  ###region Consul
  consul:
    image: fabos4ai/slm-consul:${CONSUL_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    networks:
      default:
        aliases:
          - consul
    ports:
      - "${CONSUL_PORT}:8500"
    volumes:
      - consul_data:/consul/data
      - consul_config_root:/config/root
      - consul_config_awx:/config/awx
      - consul_config_resource-registry:/config/resource_registry
      - consul_config_service-registry:/config/service_registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8500" ]
    depends_on:
      - keycloak

  consul-init:
    image: fabos4ai/slm-consul-init:${SLM_VERSION}
    restart: "no"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - consul_config_root:/config/consul/root
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  consul-esm:
    image: hashicorp/consul-esm:0.6.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - consul
    environment:
      CONSUL_HTTP_ADDR: consul:8500
    volumes:
      - consul_config_root:/consul/
    command: >
      sh -c "export CONSUL_HTTP_TOKEN=$$(cat /consul/consul_master_token) && consul-esm"
  ###endregion Consul

networks:
  default:

volumes:
  notification-service-database_data:
  notification-service-database_config:
  resource-registry-database_data:
  resource-registry-database_config:
  service-registry-database_data:
  service-registry-database_config:
  keycloak-database_data:
  keycloak-database_config:
  keycloak_config_awx-jwt-proxy:
  keycloak_config_notification-service:
  keycloak_config_resource-registry:
  keycloak_config_service-registry:
  keycloak_config_service-registry-init:
  consul_data:
  consul_config_root:
  consul_config_awx:
  consul_config_resource-registry:
  consul_config_service-registry:
  vault_data:
  vault_config_root:
  vault_config_awx:
  vault_config_awx-jwt-proxy:
  vault_config_resource-registry:
  vault_config_service-registry:
  awx_database_data:
  awx_supervisor_socket:
  awx_rsyslog_socket:
  awx_rsyslog_config:
  awx-redis:
  awx_config_notification-service:
  awx_config_resource-registry:
  awx_config_service-registry:
  awx_config_jwt-proxy:
