version: '3'

services:
  monitoring-prometheus-aas:
    image: fabos4ai/fabos-monitoring-prometheus-aas:${MONITORING_SERVICE_VERSION}
    networks:
      default:
        aliases:
          - monitoring
    ports:
      - "${MONITORING_SERVICE_PORT}:8080"

  monitoring-prometheus-configurator:
    image: fabos4ai/fabos-monitoring-prometheus-configurator:0.0.1-SNAPSHOT
    networks:
      default:
        aliases:
          - monitoring-prometheus-configurator
    ports:
      - "${MONITORING_CONFIGURATOR_PORT}:5000"
    volumes:
      - prometheus-targets:/code/targets

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    networks:
      default:
        aliases:
          - prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-targets:/etc/prometheus/targets/

volumes:
  prometheus-targets: