version: '3'

services:

  ui:
    image: fabos4ai/slm-ui:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${UI_PORT}:80"
    networks:
      default:
        aliases:
          - ui
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    environment:
      VUE_APP_KEYCLOAK_URL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
      VUE_APP_AWX_URL: "http://${SLM_HOSTNAME}:${AWX_PORT_HTTP}"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]

  resource-registry:
    image: fabos4ai/slm-resource-registry:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    ports:
      - "${RESOURCE_REGISTRY_PORT}:9010"
    networks:
      default:
        aliases:
          - resource-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - awx_config_resource-registry:/app/awx:ro
      - consul_config_resource-registry:/app/consul:ro
      - keycloak_config_resource-registry:/app/keycloak:ro
      - vault_config_resource-registry:/app/vault:ro
      - resource-registry-database_config:/app/database/config
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9010/swagger-ui/index.html" ]

  resource-registry-database:
    image: fabos4ai/mariadb:${RESOURCE_REGISTRY_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${RESOURCE_REGISTRY_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - resource-registry-database
    environment:
      MYSQL_USER: resource-registry
      MYSQL_DATABASE: resources
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - resource-registry-database_data:/var/lib/mysql
      - resource-registry-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  resource-registry-init:
    image: fabos4ai/slm-resource-registry-init:${SLM_VERSION}
    restart: "no"
    depends_on:
      - resource-registry
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  service-registry:
    image: fabos4ai/slm-service-registry:${SLM_VERSION}
    restart: unless-stopped
    depends_on:
      - service-registry-database
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
      GIT_SERVICEOFFERINGIMPORTER_UPDATERINTERVALMINUTES: ${SERVICE_REGISTRY_GIT_CHECK_INTERVAL_MINUTES}"
    ports:
      - "${SERVICE_REGISTRY_PORT}:9020"
    networks:
      default:
        aliases:
          - service-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - awx_config_service-registry:/app/awx:ro
      - consul_config_service-registry:/app/consul:ro
      - keycloak_config_service-registry:/app/keycloak:ro
      - vault_config_service-registry:/app/vault:ro
      - service-registry-database_config:/app/database/config
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9020/swagger-ui/index.html" ]

  service-registry-init:
    image: fabos4ai/slm-service-registry-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - keycloak_config_service-registry-init:/app/keycloak
    environment:
      SERVICEREGISTRY_INITDIRECTORIES: ${SERVICE_REGISTRY_INITIALIZATION_LOCAL_DIRECTORIES}
      SERVICEREGISTRY_GITREPOS_URLS: ${SERVICE_REGISTRY_INITIALIZATION_GIT_REPOS}

  service-registry-database:
    image: fabos4ai/mariadb:${SERVICE_REGISTRY_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${SERVICE_REGISTRY_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - service-registry-database
    environment:
      MYSQL_USER: service-registry
      MYSQL_DATABASE: services
    volumes:
      - service-registry-database_data:/var/lib/mysql
      - service-registry-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  notification-service:
    image: fabos4ai/slm-notification-service:${SLM_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:9001"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    networks:
      default:
        aliases:
          - notification-service
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9001/swagger-ui/index.html" ]
    volumes:
      - awx_config_notification-service:/app/awx:ro
      - keycloak_config_notification-service:/app/keycloak:ro
      - notification-service-database_config:/app/database/config

  notification-service-database:
    image: fabos4ai/mariadb:${NOTIFICATION_SERVICE_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${NOTIFICATION_SERVICE_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - notification-service-database
    environment:
      MYSQL_USER: notification-service
      MYSQL_DATABASE: notifications
    volumes:
      - notification-service-database_data:/var/lib/mysql
      - notification-service-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  ###endregion Custom Service Lifecycle Components

networks:
  default:

volumes:
  notification-service-database_data:
  notification-service-database_config:
  resource-registry-database_data:
  resource-registry-database_config:
  service-registry-database_data:
  service-registry-database_config:
