- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)

- name: "Create Keycloak realm"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms"
    method: POST
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
    body_format: json
    body: "{{ keycloak_realm }}"
    status_code: 201, 409
  changed_when: output_create_realm.status == 201
  register: output_create_realm
