- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_default_user is defined) and (keycloak_default_user|length > 0)

- name: "Set password for default user 'fabos'"
  set_fact:
    keycloak_default_user: "{{ keycloak_default_user | combine(updated_entry, recursive=true) }}"
  vars:
    updated_entry: { 'credentials': [ { 'type': 'password', 'value': '{{ keycloak_default_user_password }}', 'temporary': false } ] }
  with_dict: "{{ keycloak_default_user }}"

- name: "Create default user"
  uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ keycloak_realm }}/users"
    method: POST
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
    body_format: json
    body: "{{ keycloak_default_user }}"
    status_code: 201, 409
  register: output_post_realm_role
  changed_when: output_post_realm_role.status == 201

- name: "Assign realm roles to default users"
  include_role:
    name: "keycloak_init"
    tasks_from: assign_realm_roles_to_user.yml
  vars:
    keycloak_user: "{{ keycloak_default_user }}"
