- assert:
    that:
      - (keycloak_realm_roles is defined) and (keycloak_realm_roles|length > 0)

- name: "Create realm roles"
  include_role:
    name: "keycloak_client"
    tasks_from: roles/create_realm_role.yml
  vars:
    keycloak_realm_role: "{{ item }}"
  with_items: "{{ keycloak_realm_roles }}"
