- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_clients is defined) and (keycloak_clients|length > 0)
      - (keycloak_client_configs_store_directory is defined) and (keycloak_client_configs_store_directory|length > 0)

- include_role:
    name: keycloak_client
    tasks_from: clients/get_oidc-keycloak-json.yml
  loop: "{{ keycloak_clients }}"
  vars:
    client_id: "{{ item.client_id }}"
    output_path_local: "{{ item.oidc_installation_json_output_path_local | default('') }}"
    output_path_target_host: "{{ item.oidc_installation_json_output_path_target_host | default('') }}"

- name: "Store config for init of service registry into {{ keycloak_client_configs_store_directory  }}"
  block:
    - name: "Copy Keycloak auth server url into file '{{ keycloak_client_configs_store_directory }}/auth-server-url'"
      copy:
        content: "{{ keycloak_auth_url }}"
        dest: "{{ keycloak_client_configs_store_directory }}/auth-server-url"
    - name: "Copy Keycloak realm into file '{{ keycloak_client_configs_store_directory }}/realm'"
      copy:
        content: "{{ keycloak_realm }}"
        dest: "{{ keycloak_client_configs_store_directory }}/realm"
    - name: "Copy Keycloak username into file '{{ keycloak_client_configs_store_directory }}/username'"
      copy:
        content: "{{ keycloak_default_user.username }}"
        dest: "{{ keycloak_client_configs_store_directory }}/username"
    - name: "Copy Keycloak password into file '{{ keycloak_client_configs_store_directory }}/password'"
      copy:
        content: "{{ keycloak_default_user_password }}"
        dest: "{{ keycloak_client_configs_store_directory }}/password"
