- name: "Init FaboOS Service Lifecycle Management"
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - set_fact:
        keycloak_auth_url: "{{ lookup('env', 'KEYCLOAK_AUTHSERVERURL') }}"
        keycloak_admin_username: "{{ lookup('env', 'KEYCLOAK_ADMIN_USER') }}"
        keycloak_admin_password: "{{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD') }}"
        keycloak_default_user_password: "{{ lookup('env', 'KEYCLOAK_DEFAULT_USER_PASSWORD') }}"

    - assert:
        that:
          - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
          - (keycloak_admin_username is defined) and (keycloak_admin_username|length > 0)
          - (keycloak_admin_password is defined) and (keycloak_admin_password|length > 0)
          - (keycloak_default_user_password is defined) and (keycloak_default_user_password|length > 0)

    - name: "Create directory to store config"
      file:
        path: /config/
        state: directory

    - name: Wait for Keycloak being up
      uri:
        url: "{{ keycloak_auth_url }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 120
      delay: 3

    - include_role:
        name: keycloak_client
        tasks_from: authentication/get_admin_access_token.yml

    - name: "Create realms"
      include_role:
        name: "keycloak_init"
        tasks_from: create_realms.yml

    - name: "Create clients"
      include_role:
        name: "keycloak_init"
        tasks_from: create_clients.yml

    - name: "Create roles"
      include_role:
        name: "keycloak_init"
        tasks_from: create_roles.yml

    - name: "Create users"
      include_role:
        name: "keycloak_init"
        tasks_from: create_users.yml

    - name: "Get client secret of awx-jwt-proxy"
      block:
        - include_role:
            name: keycloak_client
            tasks_from: clients/get_client_secret.yml
          vars:
            client_id: awx-jwt-proxy
        - set_fact:
            awx_jwt_proxy_keycloak_secret_id: "{{ client_secret }}"

    - include_role:
        name: keycloak_init
        tasks_from: store_configs.yml
