name: Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push-awx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build base docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml build --no-cache awx-fixed-files
      - name: Build AWX Web docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml build --no-cache awx-web
      - name: Build AWX Web No JWT docker image
        working-directory: ./compose
        run: docker-compose -f build.yml build --no-cache awx-web-no-jwt
      - name: Build AWX Task docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml build --no-cache awx-task
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml push awx-web awx-web-no-jwt awx-task

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - common-database-mariadb
          - awx-postgres
          - awx-init
          - consul
          - consul-init
          - keycloak
          - keycloak-init
          - vault
          - vault-init
          - config-exporter
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml -f config-exporter.yml build --no-cache ${{ matrix.service }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        working-directory: ./compose
        run: docker-compose -f build.yml -f docker-compose.yml -f config-exporter.yml push ${{ matrix.service }}
