name: Docker Images

on:
  push:
    branches:
      - main
      - develop
      - release-*
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_COMPOSE_COMMAND: docker-compose -f base.awx.yml -f base.consul.yml -f base.keycloak.yml -f base.vault.yml -f slm.yml -f config-exporter.yml -f build.yml

jobs:

  build-and-push-awx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build base docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND build --no-cache awx-fixed-files
      - name: Build AWX Web docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND build --no-cache awx-web
      - name: Build AWX Web No JWT docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND build --no-cache awx-web-no-jwt
      - name: Build AWX Task docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND build --no-cache awx-task
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND push awx-web awx-web-no-jwt awx-task

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - common-database-mariadb
          - awx-postgres
          - awx-init
          - consul
          - consul-init
          - keycloak
          - keycloak-init
          - vault
          - vault-init
          - config-exporter
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND build --no-cache ${{ matrix.service }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        working-directory: ./compose
        run: $DOCKER_COMPOSE_COMMAND push ${{ matrix.service }}
